feat: 서랍장 서비스 등록 페이지 카테고리 체크박스 컴포넌트 구현 + 경고문
yourssu/Soomsil-Web pull request #63
Opened 2024-02-23 07:05 UTC by seocylucky

## 1️⃣ 어떤 작업을 했나요? (Summary)

### 등록페이지에 있는 카테고리 컴포넌트 작업
- 사이드바에 있는 카테고리와 등록페이지에 있는 카테고리 형태가 달라 `IsAllProps`를 만들어서 isAll 값에 따라 분기해서 사이드바 | 등록페이지에 쓸 수 있는 형태로 Category.tsx를 수정했습니다!!!
- 등록페이지에 있는 카테고리 컴포넌트는 CategoryWithoutAll.tsx 파일로 만들었습니다. 24.375rem을 기준으로 모바일 대응을 했는데 여기서 gap이 피그마에 맞게 하면 제일 긴 체크박스의 텍스트가 잘려서 두줄로 텍스트가 뜨는 현상...이 나타나더라구요. 그래서 gap을 쪼오금 줄이고 390 해상도에서 안잘리게 일단 만들어뒀습니다.

### 경고문 + 확인했습니다 CheckBox
- 모바일 시에는 아코디언으로 컴포넌트 자체가 바뀌게되므로 resize 이벤트를 이용해서 `window.innerwidth 값`에 따라 분기해서 컴포넌트를 띄우도록 했습니다.

### 🤔 **여기서 고민되는 점....** 
window.innerwidth로 모바일 대응을 했을 때 개발자도구로 마우스로 직접 드래그하면서 체크하면 컴포넌트가 390픽셀부터 잘 바뀌는데 기기 툴 전환 이용해서 하면 바로바로 안먹더라구요..?ㅠㅠ (새로고침해야 나옴, 비동기 문제인가...)

그래서 console.log로 값 알아보고 이유가 뭔지 찾아보니까 기기툴 전환할 때는 적용이 안되는 것 같은데 실제로 모바일 화면에서 웹을 켰을 때 저희가 원하는대로 적용이 될 지, 마우스로만 드래그했을 때만 되는 건지.. 해결사 찾습니다🥲

- resolved #48 

<img width="1500" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/94633589/9ef453b7-a4b5-4f3b-ab76-93c91da1f1ae">
<img width="391" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/94633589/05b87f3c-f381-409f-8af0-1ab52579cefb">

### 실행 영상

https://github.com/yourssu/Soomsil-Web/assets/94633589/bbf39a99-d289-44e6-9766-e0817fa7aa8b

### 기존 코드에 영향을 미치는 변경사항
 Category.tsx에 isAll props가 생겨서 카테고리 컴포넌트 쓸 때 이 부분 추가해줘야 합니다!! 기존에 사용된 사이드바 카테고리 부분에 isAll props 추가로 넣어서 Ranking.tsx파일 수정했습니다. 

## 3️⃣ 추후 작업
- api 연결

## 4️⃣ 체크리스트 (Checklist)

- [x] `main` 브랜치의 최신 코드를 `pull` 받았나요?

하다가 좀 막혔어서... 제가 깨끗하고 효율적으로 코드는 잘 못 짠 것 같아 슬프네요... 데드라인이 있기 때문에 일단 pr 스르륵 올려봅니다...
한 번 봐주시면 감사하겠습니다🥲

2024-02-23 07:17 UTC, Hanna922 commented
리뷰 전 빠른 코멘트 하나 남김니다.....!!!! 카테고리 중복 선택 불가인데 중복 선택이 되는 것 같아요~!!

2024-02-23 11:08 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningBox.style.ts
> +export const StyledWarningBoxContainer = styled.div`
잘 맞춰보겠습니다ㅎㅎㅎ

2024-02-23 11:17 UTC, seocylucky commented on src/drawer/pages/Ranking/Ranking.tsx
> +      <Category isAll={true} />
헉 slice가 들어가서 맨 앞에 "전체" 요소가 빠졌었네요!!!!! 수정했습니다아ㅎㅎㅎ

2024-02-23 11:18 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningBox.tsx
> +  const [isMobileView, setIsMobileView] = useState(window.innerWidth <= 24.375 * 16);
🥹🥹이런 칭찬하시면 저 날아당깁니다 기뻐서.......

2024-02-23 12:08 UTC, Hanna922 approved these changes
수고하셨습니당~!!

2024-02-23 12:08 UTC, Hanna922 commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.style.ts
> +  font-family: 'Apple SD Gothic Neo';
해당 폰트 피그마에서 변경 요청 드렸습니당

2024-02-23 12:14 UTC, Hanna922 requested changes

2024-02-23 12:46 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningBox.style.ts
> +  margin-right: 1.2rem;
우악 제가 꼼꼼치 못했군요 확인 감사해욧!!!!!
수정해보겠습니당

2024-02-23 14:01 UTC, Hanna922 approved these changes
수고하셨습니당~!
해당 체크박스도 우측 정렬이 필요할 것 같은데, 요건 전체 레이아웃을 감싸서 만드는 게 좋을 것 같아서 제가 레이아웃 작업할 때 같이 볼게요~!!
![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/d4b3afea-99ac-468b-b419-0817823013e5)

2024-02-24 17:26 UTC, 2wndrhs reviewed
수고하셨어요 👍👍

구현이 굉장히 까다로웠을 것 같네요😮

2024-02-24 17:26 UTC, 2wndrhs commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.style.ts
> +`;
Accordion 열릴 때 애니메이션이 추가되면 좋을 것 같아요!

```suggestion
  margin-top: ${({ $isOpen }) => ($isOpen ? '1.31rem' : '0')};
  max-height: ${({ $isOpen }) => ($isOpen ? '500px' : '0')};
  overflow: hidden;
  transition:
    max-height 0.2s ease-out,
    margin-top 0.2s ease-out;
```

2024-02-25 03:27 UTC, seocylucky commented on src/drawer/components/Category/Category.tsx
> +            >{`${title}${subcategories ? ` ${subcategories}` : ''}`}</CheckBox>
오 병합 연산자는 잘 안써봤어서..!! 보기 더 깔끔하네요ㅎㅎㅎ 이걸루 가겠습니다~!

2024-02-25 03:47 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.tsx
> +export const WarningAccodion = () => {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ인간 Code Spell Checker 네요.... 익스텐션 깔아보도록 하겠습니다....ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 상수 너무 좋은 생각 같아요 바로 적용할게요~!~!

2024-02-25 03:48 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.tsx
> +        </IconContext.Provider>
와 대박 저 아이콘 바뀌는 거 이제 알았어요...... 감사합니다...........

2024-02-25 03:50 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.tsx
> +        </IconContext.Provider>
![image](https://github.com/yourssu/Soomsil-Web/assets/94633589/e078e6b8-f3db-43d4-91df-f9b325649985)

2024-02-25 04:04 UTC, seocylucky commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.style.ts
> +`;
오!!! 애니메이션 넣으면 좋을 거 같은데 현재 제 코드상으로 StyledAccordionContainer의 height가 fit-content로 되어 있어서 StyledAccordionContent의 내용물에 따라 높이가 달라지게 해놓은 상태인데..! 아코디언 박스들이 두개로 분기되어 있다면 애니메이션 처리가 가능할 것 같은데 이건 하나의 StyledAccordionContainer의 높이가 달라지는 거여서요!! 저희가 원하는 느낌의 애니메이션 넣을라믄 구조를 좀 바꿔야해서..

애니메이션 처리는.... 조금 후순위로 하면 어떨지... 조심스레 이야기해봅니다ㅎㅎ 호홓

2024-02-25 06:43 UTC, 2wndrhs commented on src/drawer/components/WarningBox/WarningAccodion/WarningAccodion.style.ts
> +`;
아하 그런 문제가 있었군요 그렇다면 애니메이션 적용은 추후에 하는걸로..

2024-02-25 06:44 UTC, 2wndrhs approved these changes

2024-02-25 11:25 UTC, merged